### ISSUE TITLE
#pragma mark not converted when  inside classes

### ISSUE THREAD

**Issue by bre7** [drkameleon/iswift#48] opened 2015-09-04 20:12 UTC
Example:
```objectivec
@implementation SomeClass
    #pragma mark SomeComment

    ...
@end
```

Expected output:
```swift
class SomeClass
    // MARK: SomeComment

    ...
@end
```

Result: **Error**

**Comment by drkameleon** [comment] 2015-09-04 20:42
Good catch. Let's see what I can do... :)

**Comment by drkameleon** [comment] 2015-09-09 17:52
Fixed as of the upcoming 1.6.

**Comment by bre7** [comment] 2015-09-19 04:13
Same error when they are between `@interface ~ @end`

**Comment by drkameleon** [comment] 2015-09-19 04:16
Hm Hmm Hmm... I must have missed somethings. :S

I'll look into it and will let you know - for now I'm re-opening the issue.

**Comment by drkameleon** [comment] 2015-09-23 09:43
Can you please veryify it is NOT working? I cannot reproduce that... For me, it seems to be working fine.

![screen shot 2015-09-23 at 11 43 01 am](https://cloud.githubusercontent.com/assets/1265028/10041905/45a7ad5c-61e8-11e5-932c-e541e6eb8a7d.png)

**Closed** 2015-09-24 10:34 UTC
Labels: bug
